### ISSUE TITLE
Option für ein Blitzlicht

### ISSUE THREAD

**Issue by mrlaja-zz** [MacAndMoreYT/Photoboth#1]
Hallo, erstmal Glückwunsch!  super Projekt!

Ich möchte bald dieses Projekt aufbauen. Jedoch würde ich das ganze noch um einen Blitz erweitern wollen. Nur kann ich selbst nicht programmieren. Wie könnte man das umsetzen?

**Comment by nickhildebrandt** [comment]
Vielen Dank für dein Interesse an meinem Projekt,
die Funktion für ein Blitzlicht ist bereits Intergiert und kann in der config.json abgerufen werden.
```json
    "foto":
                {
                **"light":"ON",**
                "fps":30,
                "pic":".png",
        	"path":"/home/pi/data/"
                }
```
Um dann eine normale Lampe anzusteuern nimmst du einfach Relais [(diese verwende ich.)](https://www.amazon.de/ARCELI-ST%C3%9CCKE-KY-019-Relaismodul-arduino/dp/B07BVXT1ZK/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=relais&qid=1622896056&sr=8-3)
An einem genauen Schaltplan sowie der Anleitung wird bereits gearbeitet. Diese werden dann in der finalen Version hinzugefügt. Dann wird das Programm auch als .deb bereitgestellt, um die Installation zu vereinfachen. Da es in spätestens 2 Wochen die Finale Version geben wird, würde ich dir empfehlen zu warten.
