### ISSUE TITLE
keine install.sh

### ISSUE THREAD

**Issue by mrlaja-zz** [MacAndMoreYT/Photoboth#2]
Hallo, in meinem Photoboth Ordner befindet sich keine install.sh
hab ich was falsch gemacht?

**Comment by nickhildebrandt** [comment]
Nee inzwischen wird die .deb Datei verwendet (Neue Anleitung kommt)
https://github.com/MacAndMoreYT/Photoboth/blob/master/deb/photoboth_1_all.deb

**Comment by nickhildebrandt** [comment]
OK, Beschreibung ist Aktuell und der Finale Version 1.0 ist raus.

**Comment by mrlaja-zz** [comment]
Super. Funktioniert. Vielen Dank für ihre Arbeit...
