### ISSUE TITLE
Keine Fotos in 8MP möglich

### ISSUE THREAD

**Issue by mrlaja-zz** [MacAndMoreYT/Photoboth#3]
Hallo, ich kann keine Bilder in der vollen Auflösung der Kamera(3280 x 2464 Pixel) aufnehmen! ist das irgendwie möglich?

**Comment by nickhildebrandt** [comment]
Also grundsätzlich sollte die Aufnahmeauflösung im gleichen Seitenverhältnis wie das Display, auf dem die Vorschau angezeigt wird, liegen. Zudem gibt es mit deiner Auflösung Probleme beim PI, wie [hier](https://www.raspberrypi.org/forums/viewtopic.php?t=196145) beschrieben.
### Beispiele für mögliche Auflösungen:
- 1920 x 1080 -> 16:9
- 1600 x 1200 -> 4:3
- 1440 x 900 -> 16:10
- 1600 x 960 -> 15:9 <- (800 x 480 - Pi 7"Display)

**Comment by mrlaja-zz** [comment]
Also ist es nicht möglich ein größeres Bild aufzunehmen, als mein Bildschirm darstellen kann? 
Ich habe leider nur einen 1280x720 Monitor zum verbasteln. Die Bilder sollten aber schon Besser werden...

mit "raspistill -o ~/home/pi/data/test.jpg" klappt es aber ohne Probleme in voller Auflösung...

Ich bin leider hauptsächlich Hardware-Bastler, Software ist meistens nur Copy&Paste- Sorry

mfG Jan

**Comment by nickhildebrandt** [comment]
Es ist selbstverständlich möglich, Bilder aufzunehmen, die höher auflösen als das Display. Jedoch ist dabei zu beachten, dass wie gesagt das Seitenverhältnis bestehen bleibt. So kannst du zum Beispiel deine Auflösung (1280 × 720) verdoppelt und hast immer noch das gleiche Seitenverhältnis mit Richter Vorschau nur eben in doppelter Auflösung. Bei deinem Beispiel wären es dann 2560 x 1440 bei 16:9 was WQHD (UHD) entspricht.

**Comment by mrlaja-zz** [comment]
OK, die Auflösung reicht mir. Dann Hätte ich noch eine Frage: das Relais für die Beleuchtung ist manchmal 15 Sekunden geschaltet. Braucht der Pi wirklich so lang, um ein Foto zu machen....? oder kann ich diese Zeit  irgendwie anpassen? 

mfG

**Comment by nickhildebrandt** [comment]
Die Belichtungszeit hängt mit der Geschwindigkeit des verwendeten Kamerasensors zusammen. Da alle Pikameramodule unterschiedlich reagieren, habe ich mich dazu entschieden, eine solch lange zeit fest im Code zu verankern. Wenn du willst, kannst du aber in der opt/photoboth/photoboth.py den Quellcode ändern (Mit darauffolgenden System Neustart):
### Standard Code:
```python:
			if not GPIO.input(BUTTON_GPIO):
				if not pressed:
					if light == "ON":
						GPIO.output(LAMPE_GPIO, True)
					text(text = three)
					time.sleep(sleep_time)
					text(text = two)
					time.sleep(sleep_time)
					text(text = one)
					time.sleep(sleep_time)
					filename = time.strftime("%Y%m%d-%H%M%S") + (pic)
					sorce = path + filename
					dest = upath + filename 
					text(text = " ")
					camera.capture(sorce, use_video_port=False)
```
### Angepasste Version mit späterem Blitz:
```python:
			if not GPIO.input(BUTTON_GPIO):
				if not pressed:
					text(text = three)
					time.sleep(sleep_time)
					text(text = two)
					time.sleep(sleep_time)
					text(text = one)
					time.sleep(sleep_time)
					if light == "ON":
						GPIO.output(LAMPE_GPIO, True)
					filename = time.strftime("%Y%m%d-%H%M%S") + (pic)
					sorce = path + filename
					dest = upath + filename 
					text(text = " ")
					camera.capture(sorce, use_video_port=False)
```

**Comment by mrlaja-zz** [comment]
> Die Belichtungszeit hängt mit der Geschwindigkeit des verwendeten Kamerasensors zusammen. Da alle Pikameramodule unterschiedlich reagieren, habe ich mich dazu entschieden, eine solch lange zeit fest im Code zu verankern. Wenn du willst, kannst du aber in der opt/photoboth/photoboth.py den Quellcode ändern (Mit darauffolgenden System Neustart):
> ### Standard Code:
> 
> ```
> 			if not GPIO.input(BUTTON_GPIO):
> 				if not pressed:
> 					if light == "ON":
> 						GPIO.output(LAMPE_GPIO, True)
> 					text(text = three)
> 					time.sleep(sleep_time)
> 					text(text = two)
> 					time.sleep(sleep_time)
> 					text(text = one)
> 					time.sleep(sleep_time)
> 					filename = time.strftime("%Y%m%d-%H%M%S") + (pic)
> 					sorce = path + filename
> 					dest = upath + filename 
> 					text(text = " ")
> 					camera.capture(sorce, use_video_port=False)
> ```
> 
> ### Angepasste Version mit späterem Blitz:
> 
> ```
> 			if not GPIO.input(BUTTON_GPIO):
> 				if not pressed:
> 					text(text = three)
> 					time.sleep(sleep_time)
> 					text(text = two)
> 					time.sleep(sleep_time)
> 					text(text = one)
> 					time.sleep(sleep_time)
> 					if light == "ON":
> 						GPIO.output(LAMPE_GPIO, True)
> 					filename = time.strftime("%Y%m%d-%H%M%S") + (pic)
> 					sorce = path + filename
> 					dest = upath + filename 
> 					text(text = " ")
> 					camera.capture(sorce, use_video_port=False)
> ```

**Comment by mrlaja-zz** [comment]
die Lampe ist trotzdem noch 10 Sekunden an. Da ist mein Pi3 wohl zu langsam...
